### ISSUE TITLE
A Java Exception Has Occurred

### ISSUE THREAD

**Issue by Admiralfiggins** [The-1-7-10-Pack/The-1.7.10-Pack#76]
Hey so I've been trying to set up my own private server but I can't get the .jar file to do anything but tell me "A Java Exception Has Occurred" I've tried deleting and re-downloading minecraft version 1.7.10 and deleting and retrying the server files and updated my java to 8 and also downloaded the jdk 7u71 and 7u72 this is what i get:

OS is 64
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; sup
port was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128M; suppor
t was removed in 8.0
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.ExceptionInInitializerError
        at org.apache.logging.log4j.util.PropertiesUtil.<init>(PropertiesUtil.ja
va:71)
        at org.apache.logging.log4j.util.PropertiesUtil.<clinit>(PropertiesUtil.
java:31)
        at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.ja
va:48)
        at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:44)
        at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.ja
va:14)
        at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.apache.logging.log4j.util.ProviderUtil.<clinit>(ProviderUtil.java
:70)
        ... 14 more
Press any key to continue . . .

Any ideas on how to correct that?

**Comment by darktrek** [comment]
hi Admiralfiggins, 

i had the very same issue as you i was told to completely uninstall java 8 64 and 32 bits off my computer and put java 7 tu71 32 and 64 bit, once i did that i could load up the server hops this helps. if not i hope you get an answer soon

**Comment by The-1-7-10-Pack** [comment]
To launch the server you need to click on LaunchServer.exe.

**Comment by Admiralfiggins** [comment]
so I uninstalled all java except for 7 tu71 and still no dice :(

And I dont have a LaunchServer.exe, there is just a LaunchServer.bat (which i tried) and a LaunchServer.sh file. is thats what causing the issue?

**Comment by The-1-7-10-Pack** [comment]
So you clicked on LaunchServer.bat and you get the error mentioned above.
You have Java 64bit, but you have Java 8 as I understand?

**Comment by Admiralfiggins** [comment]
Yes, I have both Java 8 and a couple Java 7 versions

**Comment by The-1-7-10-Pack** [comment]
You should not have more than one version of Java installed. You should delete all versions and install the latest version of Java 7 64bit. This is the problem.

**Comment by Admiralfiggins** [comment]
Okay,  and 7 u71 is the latest Java 7 version?

**Comment by The-1-7-10-Pack** [comment]
I'm not sure, just uninstall all the Java versions and install a clean one from their website, it will ensure that you also have the latest version.

**Comment by Admiralfiggins** [comment]
Alright, I should have done a clean install previously for sure.  I'll go
ahead and try it when I get off work then!

**Comment by Admiralfiggins** [comment]
so I uninstalled all java versions and then installed 7 u72 and it still brought up the same error above :(

**Comment by The-1-7-10-Pack** [comment]
Are you sure? so you maybe didn't uninstall the Java 8, because this error can occur only with Java 8.

**Comment by Admiralfiggins** [comment]
Yeah the top 2 line are gone so it no longer says 

"Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; sup
port was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128M; suppor
t was removed in 8.0"

now it says  

OS is 64
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.ExceptionInInitializerError
        at org.apache.logging.log4j.util.PropertiesUtil.<init>(PropertiesUtil.ja
va:71)
        at org.apache.logging.log4j.util.PropertiesUtil.<clinit>(PropertiesUtil.
java:31)
        at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.ja
va:48)
        at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:44)
        at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.ja
va:14)
        at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.apache.logging.log4j.util.ProviderUtil.<clinit>(ProviderUtil.java
:70)
        ... 14 more
Press any key to continue . . .

**Comment by The-1-7-10-Pack** [comment]
Can you post the the actual full log on http://pastebin.com?

**Comment by Admiralfiggins** [comment]
Where would I find the log?

**Comment by The-1-7-10-Pack** [comment]
logs/fml-server-latest.log

**Comment by Admiralfiggins** [comment]
Mine doesn't have a log file :/

**Comment by The-1-7-10-Pack** [comment]
I just don't have enough information.
You click the "LaunchServer.bat" and you get an error? or is it showing on the console?

**Comment by Admiralfiggins** [comment]
Yes, all the above is what pops up on the. Bat launcher. So it doesn't even
create the world or anything

**Comment by The-1-7-10-Pack** [comment]
And you don't have any "logs" folder?

**Comment by Admiralfiggins** [comment]
No logs folder, when it didn't add any world file or anything it's like it
fails before it can add anything.

Also I can load up your modpack without any problems

**Comment by The-1-7-10-Pack** [comment]
There should be a logs folder even though there isn't a world folder.
Please double check, it make no sense.

**Comment by Admiralfiggins** [comment]
This is what it looks like when I transferred the server file over

**Comment by Admiralfiggins** [comment]
![1 7 10 step 1](https://cloud.githubusercontent.com/assets/10570523/5849834/ee102f46-a19f-11e4-8a0c-b9eb213cd58e.jpg)

**Comment by Admiralfiggins** [comment]
and this is what it looked like after

**Comment by Admiralfiggins** [comment]
![1 7 10 step 2](https://cloud.githubusercontent.com/assets/10570523/5849839/fdeeab22-a19f-11e4-9a03-0b277c544792.jpg)

**Comment by The-1-7-10-Pack** [comment]
Well now I see a diffrent error. You should re-download the server files and try again, because this error shows that there's a missing file.

**Comment by Flukethoughts** [comment]
Java 8 wont use these perms try pointing the bat file to the java 7 directory. if you need a guide im sure you could find one online. Java 8 had a few changes one of them was no perm size function.

**Comment by Admiralfiggins** [comment]
So I did the tweaks you asked and it worked!!! Absolutely loving the modpack!

**Comment by The-1-7-10-Pack** [comment]
:)
