### ISSUE TITLE
Tesselation error with 0.7.9c

### ISSUE THREAD

**Issue by SKleen75** [The-1-7-10-Pack/The-1.7.10-Pack#764]
Hi.
After Update from 0.7.8 to 0.7.9c my client closes right after going onto my map.

Description: Rendering Block Entity

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
	at net.minecraftforge.client.model.obj.WavefrontObject.renderAll(WavefrontObject.java:181)
	at jds.bibliocraft.models.OBJBookcase.render(OBJBookcase.java:21)
	at jds.bibliocraft.rendering.TileEntityBookcaseRenderer.func_147500_a(TileEntityBookcaseRenderer.java:101)

After that i used MCEDIT to delete the Bookcases, that i was looking at and now i get this

Time: 20.07.15 23:06
Description: Rendering Block Entity

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
	at codechicken.lib.render.CCRenderState.startDrawing(CCRenderState.java:418)
	at codechicken.chunkloader.TileChunkLoaderRenderer.func_147500_a(TileChunkLoaderRenderer.java:92)

I am lost here. Please help.

Thank you.

**Comment by The-1-7-10-Pack** [comment]
Something in Bibliocraft is bugged. I should report this.
Anyway, the easier way would be to delete the Bibliocraft mod and all its addons, load the world (it'd delete all this mod's blocks) and then add the mod back.
It shouldn't be a bug in the pack.
