### ISSUE TITLE
Server randomly closes on VPS

### ISSUE THREAD

**Issue by Sevario** [The-1-7-10-Pack/The-1.7.10-Pack#766]
I have a vps on which I try to run the 1.7.3 modpack on, but after being able to connect, a while later it's just offline, logging onto my debian vps and going to my server screen I see this:

[10:14:10] [Server thread/INFO] [Waila]: Player GCEntityPlayerMP['Sevario'/1728, l='world', x=1107.93, y=70.00, z=632.81] connected. Sending ping [10:14:10] [Server thread/INFO] [Mekanism]: Sent config to 'Sevario.' [10:14:16] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 19238ms behind, skipping 384 tick(s) [10:14:28] [Netty IO #3/ERROR] [FML]: NetworkDispatcher exception java.io.IOException: Connection reset by peer at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.7.0_80] at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.7.0_80] at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.7.0_80] at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[?:1.7.0_80] at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:492) ~[?:1.7.0_80] at io.netty.buffer.UnpooledUnsafeDirectByteBuf.getBytes(UnpooledUnsafeDirectByteBuf.java:408) ~[UnpooledUnsafeDirectByteBuf.class:?] at io.netty.buffer.UnpooledUnsafeDirectByteBuf.readBytes(UnpooledUnsafeDirectByteBuf.java:414) ~[UnpooledUnsafeDirectByteBuf.class:?] at io.netty.channel.socket.nio.NioSocketChannel.doWriteBytes(NioSocketChannel.java:214) ~[NioSocketChannel.class:?] at io.netty.channel.nio.AbstractNioByteChannel.doWrite(AbstractNioByteChannel.java:178) ~[AbstractNioByteChannel.class:?] at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:231) ~[NioSocketChannel.class:?] at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:680) ~[AbstractChannel$AbstractUnsafe.class:?] at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:260) ~[AbstractNioChannel$AbstractNioUnsafe.class:?] at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:649) ~[AbstractChannel$AbstractUnsafe.class:?] at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1038) ~[DefaultChannelPipeline$HeadHandler.class:?] at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ChannelOutboundHandlerAdapter.class:?] at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ChannelOutboundHandlerAdapter.class:?] at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ChannelOutboundHandlerAdapter.class:?] at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?] at cpw.mods.fml.common.network.handshake.NetworkDispatcher.flush(NetworkDispatcher.java:447) ~[NetworkDispatcher.class:?] at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:700) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?] at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80] [10:14:28] [Server thread/INFO]: Sevario lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}} [10:14:28] [Server thread/INFO]: Sevario left the game [10:14:31] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 15214ms behind, skipping 304 tick(s) [10:14:36] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4557ms behind, skipping 91 tick(s) [10:18:43] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 187655ms behind, skipping 3753 tick(s) [10:18:50] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 7074ms behind, skipping 141 tick(s) [10:19:16] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 16799ms behind, skipping 335 tick(s) [10:19:21] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4639ms behind, skipping 92 tick(s) [10:20:25] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 50913ms behind, skipping 1018 tick(s) [10:20:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 7147ms behind, skipping 142 tick(s) [10:23:12] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 122604ms behind, skipping 2452 tick(s) [10:23:17] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5063ms behind, skipping 101 tick(s) [10:23:49] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 20781ms behind, skipping 415 tick(s) [10:23:54] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4817ms behind, skipping 96 tick(s) [10:24:38] [Server thread/INFO] [STDOUT]: [com.sirolf2009.necromancy.generation.villagecomponent.ComponentVillageCemetery:func_74875_a:51]: Necromod generating structure, at: 22964,73,26 [10:24:38] [Server thread/INFO] [STDOUT]: [com.sirolf2009.necromancy.generation.villagecomponent.ComponentVillageCemetery:func_74875_a:51]: Necromod generating structure, at: 22964,73,26 [10:24:38] [Server thread/INFO] [STDOUT]: [com.sirolf2009.necromancy.generation.villagecomponent.ComponentVillageCemetery:func_74875_a:51]: Necromod generating structure, at: 22964,73,26 [10:24:38] [Server thread/INFO] [STDOUT]: [com.sirolf2009.necromancy.generation.villagecomponent.ComponentVillageCemetery:func_74875_a:51]: Necromod generating structure, at: 22964,73,26 [10:25:34] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 74307ms behind, skipping 1486 tick(s) [10:25:38] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4238ms behind, skipping 84 tick(s) [10:27:42] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 89053ms behind, skipping 1781 tick(s) [10:27:48] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5439ms behind, skipping 108 tick(s) [10:29:05] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 54886ms behind, skipping 1097 tick(s) [10:29:12] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6968ms behind, skipping 139 tick(s) ./LaunchServer.sh: line 2: 16085 Killed java -server -Xmx3G -XX:PermSize=256M -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1481-1.7.10-universal.jar nogui

I restarted it a few times and it just does the same.

**Comment by The-1-7-10-Pack** [comment]
It's not the full log, but as I see it now your server is just under a **very high overload**.

**Comment by Sevario** [comment]
Ah, I just realised my vps only has 2 GB ram ): that's not enough is it?

**Comment by Sevario** [comment]
I have question, I am now running the server on 2GB ram and it works properly, will this generate issues? I am planning on only having 2 players on it.

**Comment by The-1-7-10-Pack** [comment]
Well it is hard to say. It depends on how much hard time will you give the server.
3 is really recommended, but 2 may indeed work. You can test yourself I suppose :)
